name: CI/CD Dev

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE: ghcr.io/Teckio-Software/teckio_frontend
      BUILD_CONTEXT: frontend/teckio_frontend   # <— antes se llamaba DOCKER_CONTEXT

    steps:
      - name: Checkout (git clone con GITHUB_TOKEN)
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git repo
          cd repo
          echo "GIT SHA: $(git rev-parse --short HEAD)"

      - name: Asegurar docker context por defecto
        run: docker context use default

      - name: Login a GHCR (con GITHUB_TOKEN)
        working-directory: repo
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & Push
        working-directory: repo
        run: |
          TAG_DEV=dev
          TAG_SHA=sha-${GITHUB_SHA}
          docker build -t $IMAGE:$TAG_DEV -t $IMAGE:$TAG_SHA "$BUILD_CONTEXT"
          docker push $IMAGE:$DEV
          docker push $IMAGE:$TAG_SHA

      - name: Deploy al droplet por SSH
        working-directory: repo
        run: |
          echo "${{ secrets.DO_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem "${{ secrets.DROPLET_USER }}"@"${{ secrets.DROPLET_HOST }}" \
            'export GHCR_USER="${{ secrets.GHCR_USER }}"; export GHCR_TOKEN="${{ secrets.GHCR_TOKEN }}"; bash /srv/teckio/deploy-dev.sh'
