name: CI/CD Dev (no marketplace)

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE: ghcr.io/Teckio-Software/teckio_frontend   # <org>=Tu org, <service>=frontend|backend|sso
      DOCKER_CONTEXT: frontend/teckio_frontend                # cambia si tu Dockerfile está en subcarpeta (ej: frontend/teckio_frontend)

    steps:
      - name: Checkout (git clone)
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git repo
          cd repo
          echo "GIT SHA: $(git rev-parse --short HEAD)"

      - name: Login to GHCR
        working-directory: repo
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & Push
        working-directory: repo
        run: |
          TAG_DEV=dev
          TAG_SHA=sha-${GITHUB_SHA}
          docker build -t $IMAGE:$TAG_DEV -t $IMAGE:$TAG_SHA "$DOCKER_CONTEXT"
          docker push $IMAGE:$TAG_DEV
          docker push $IMAGE:$TAG_SHA

      - name: Deploy over SSH
        working-directory: repo
        run: |
          echo "${{ secrets.DO_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem "${{ secrets.DO_SSH_USER }}"@"${{ secrets.DO_HOST }}" \
            'export GHCR_USER="${{ secrets.GHCR_USER }}"; export GHCR_TOKEN="${{ secrets.GHCR_TOKEN }}"; bash /srv/teckio/deploy-dev.sh'
